apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-pvc.yaml
  - grafana-datasource-cm.yaml
  - grafana-provider-cm.yaml

configMapGenerator:
  - name: podinfo-dashboard-cm
    namespace: prometheus
    files:
      - podinfo-dashboard.json
generatorOptions:
  disableNameSuffixHash: true