apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
data:
  alertmanager.yml: |
    route:
      receiver: "gmail"

    receivers:
      - name: "gmail"
        email_configs:
          - to: "mohamedzaahran1@gmail.com"
            from: "mohamedzaahran1@gmail.com"
            smarthost: "smtp.gmail.com:587"
            auth_username: "mohamedzaahran1@gmail.com"
            auth_identity: "mohamedzaahran1@gmail.com"
            auth_password: "fslwhxqntoiovqbp"
            require_tls: true