apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: prometheus
data:
  alert.rules.yml: |
    groups:
      - name: pod-health
        rules:
          - alert: PodInfoScrapeDown
            expr: up{job="kubernetes-pods", namespace="podinfo"} == 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Podinfo scrape target is down"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is down (instance {{ $labels.instance }}) for more than 1 minute."